import "../../app/globals.css";
import { Inter } from "next/font/google";
import { AuthUserProvider } from "../../../firebase/Auth";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { ProductDataProvider } from "./ProductDataContext/ProductDataContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={` ${inter.className}`}>
        <ProductDataProvider>
        <AuthUserProvider>
          <Navbar />
          <ToastContainer />
          {children}
          <Footer />
        </AuthUserProvider>
        </ProductDataProvider>
        
      </body>
    </html>
  );
}
